language: generic
sudo: required

services: 
  - docker
before install:
  - docker build -t chenchih/docker-react -f Dockerfile.dev . 
script:
  - docker run -e CI=true chenchih/docker-react npm run test
  
